### ISSUE TITLE
Type Checking

### ISSUE THREAD

**Issue by JamesPhillipsUK** [DylanSingleton/TicTacToe#1]
Hi Dylan.  
It might be worth checking the data type of input values from the user:
# Example error: - running TicTacToe.py
```
Python 2.7.10 (default, Jul 14 2015, 19:46:27)
[GCC 4.8.2] on linux
   
--------------------------------------------------------------------------------
            Welcome to my TicTacToe game. Created by Dylan Singleton            
--------------------------------------------------------------------------------
Press 1: to START GAME. 
Press 2: To CHECK SCORE. 
Press 3: To EXIT GAME. 
Please select one:  q
Traceback (most recent call last):
  File "python", line 156, in <module>
  File "python", line 12, in menu
  File "<string>", line 1, in <module>
NameError: name 'q' is not defined
```
![dylanbug](https://cloud.githubusercontent.com/assets/18355858/25253703/f5802c62-2619-11e7-916e-92df9906b56d.PNG)
When the input type doesn't match the expected type, the app returns an error.
Cheers!

# On an unrelated topic
Since you've started on GitHub, I thought you might be interested in this article form the FSF: http://www.fsf.org/licensing/ .  The "Guide to choosing a license for your own work" link is especially useful for free software licensing.
 - James. @JamesPhillipsUK

**Comment by DylanSingleton** [comment]
Cheers mate, fixed the issue. I'll definitely give them a read, thanks!
